[project]
name = "sentra_cli"
version = "0.0.1"
description = "Projet sentra_cli"

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E","F","I","B","UP"]